/** PROJECT EULER PROBLEM 2: EVEN FIBONACCI NUMBERS
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms. **/

var makeFibonacci = function(maxFibonacci) { //Generates the Fibonacci sequence up to a given term in the sequence
    var fibonacci = [1, 2];
    for (var i = 0; i <= maxFibonacci; i++) {
        console.log(fibonacci[i] + fibonacci[i+1]);
    };
};